### ISSUE TITLE
Running the bot in background

### ISSUE THREAD

**Issue by nabil-ha** [wilschmidtt/video-watch-bot#1]
Is there a way to run the bot in background?

**Comment by wilschmidtt** [comment]
Unfortunately with the current code there is there is no way to run it in the background. The PyAutoGUI library takes over your mouse, and it will interfere with whatever else you are doing. With this in mind, I just ran the program overnight. 

Something worth exploring though is injecting JavaScript code and using this to execute button clicks instead of having the mouse click the buttons. YouTube may spot this and flag it right away though. I would've tested this but I have no experience writing JS.

**Comment by nabil-ha** [comment]
Cool, Thank you, Just one more question. Do I have to use Nord VPN?

**Comment by wilschmidtt** [comment]
No you don't have to use NordVPN. If you don't want to use it, you can go ahead and comment out line 306 of the program in the 'src' folder. Line 306 reads: 'establish_proxy(commands)'. Also, if you have another way of establishing a rotating proxy, you could change the 'establish_proxy()' function to fit your needs. It is recommended that you use some form of a rotating proxy though because YouTube can easily spot unusual traffic coming from a single IP address.

**Comment by nabil-ha** [comment]
Thanks!
